config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('detail/', include('src.apps.detailchannel.urls', namespace='detail')),
    path('newchannel/', include('src.apps.newchannel.urls', namespace='newchannel')),
    path('search/', include('src.apps.search.urls', namespace='search')),
    path('profile/', include('src.apps.profile.urls', namespace='profile')),
    path('register/', include('src.apps.register.urls', namespace='register')),
    path('login/', include('src.apps.login.urls', namespace='login')),
    path('', include('src.apps.home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

src/apps/detailchannel/urls.py
from django.urls import path
from .views import Detail, Check

app_name = 'detail'

urlpatterns = [
    path('<int:pk>/', Detail.as_view(), name='detail_page'),
    path('<int:pk>/checkpassword/', Check.as_view(), name='check_page'),
]

src/apps/profile/urls.py
from django.urls import path
from .views import Profile


app_name = 'profile'


urlpatterns = [
    path('<str:name>/', Profile.as_view(), name='profile_page'),
]

src/models/message/models.py
from django.db import models
from django.contrib.auth import get_user_model
from src.models.channel.models import Channel

User = get_user_model()


class Message(models.Model):
    who     = models.ForeignKey(User, on_delete=models.CASCADE)
    text    = models.TextField(blank=False)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    create  = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return f"{self.text}"

src/apps/detailchannel/views.py
from django.views import View
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from src.models.channel.models import Channel
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, reverse, get_object_or_404, redirect


class Detail(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            channel = get_object_or_404(Channel, pk=kwargs.get('pk'))
            if not channel.password:
                return render(request, 'detailchannel/detail.html', {'channel': channel})
            if self.request.user == channel.author or self.request.user in channel.peoples.all():
                return render(request, 'detailchannel/detail.html', {'channel': channel})
            else:
                return redirect(reverse('detail:check_page', kwargs={'pk': channel.pk}))
        else:
            return HttpResponseRedirect('/login/')




class Check(View):

    def get(self, request, *args, **kwargs):
        channel = get_object_or_404(Channel, pk=kwargs.get('pk'))
        if self.request.user == channel.author or self.request.user in channel.peoples.all():
            return render(request, 'detailchannel/detail.html', {'channel': channel})
        return render(request, 'detailchannel/checkpassword.html', {})


    def post(self, request, *args, **kwargs):
        channel = get_object_or_404(Channel, pk=kwargs.get('pk'))
        password = request.POST.get('password')
        if check_password(password, channel.password):
            channel.peoples.add(request.user)
            return HttpResponse()
        return HttpResponseBadRequest()

src/apps/templates/detailchannel/checkpassword.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'header.html' %}

    <div class="checkpassword_container">
        <h4>CHECK PASSWORD</h4>
        <form class="checkpassword_form">{% csrf_token %}
            <label class='password_required'>Password required</label>
            <input class='password_check' type="password" placeholder="Password ..." />
            <button>CHECK PASSWORD</button>
        </form>
    </div>

<script src="{% static 'js/checkpassword.js' %}"></script>
{% endblock %}

src/apps/templates/detailchannel/detail.html
{% extends 'base.html' %}

{% block content %}

    {% include 'header.html' %}


    <div class="detail_container">
        <div class="detail_users">
            <h4>List users</h4>
            <div class="detail_users_wrapper">
                {% if channel.peoples.all %}
                    {% for people in channel.peoples.all %}
                        <a href="{% url 'profile:profile_page' name=people.username %}">{{people.username}}</a><br/>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        <div class="chat_container">
            <h4>{{channel.name}}</h4>
            <div class="chat_container_wrapper">
                {% for message in channel.message_set.all %}
                <div class="chat_item">
                    <a href="{% url 'profile:profile_page' name=message.who.username %}">{{message.who.username}}</a>
                    <p>{{message.text}}</p>
                </div>
                {% endfor %}
            </div>
            <div class="form_addnew_message">
                <form class="form_addnew">
                    <input class='text_message' type="text" placeholder="new message ..." />
                    <button type="button" name="button">SEND</button>
                </form>
            </div>
        </div>
    </div>


<script type="text/javascript">

    $(function(){
        let loc = window.location;
        let wsStart = 'ws://';
        if(loc.protocol == 'https:') {
            wsStart = 'wss://';
        }
        let endPoint = wsStart + loc.host + loc.pathname
        let wsMsg = new WebSocket(endPoint);
        wsMsg.onopen = function(e) {console.log("OpenMSG", e)}

         wsMsg.onmessage = function(e) {
             let data = JSON.parse(e.data)
             $('.chat_container_wrapper')
                .append(`<div class="chat_item">
                   <a href=''>${data['username']}</a>
                   <p>${data['message']}</p>
                   </div>`);
         }


        $('.form_addnew').on('submit', (e)=> {
            e.preventDefault();
            let text = $('.text_message').val();

            if(text) {
                console.log(text);
                let data = {'message': text}
                wsMsg.send(JSON.stringify(data))
                $('.form_addnew')[0].reset();
            }
        })
    })


</script>


{% endblock %}