config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('detail/', include('src.apps.detailchannel.urls', namespace='detail')),
    path('newchannel/', include('src.apps.newchannel.urls', namespace='newchannel')),
    path('search/', include('src.apps.search.urls', namespace='search')),
    path('profile/', include('src.apps.profile.urls', namespace='profile')),
    path('register/', include('src.apps.register.urls', namespace='register')),
    path('login/', include('src.apps.login.urls', namespace='login')),
    path('', include('src.apps.home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

src/apps/home/urls.py
from django.urls import path
from .views import Index
from src.apps.login.views import exit

app_name = 'home'

urlpatterns = [
    path('logout/', exit, name='exit_page'),
    path('', Index.as_view(), name='home_page'),
]

src/apps/profile/urls.py
from django.urls import path
from .views import Profile


app_name = 'profile'


urlpatterns = [
    path('<str:name>/', Profile.as_view(), name='profile_page'),
]

src/apps/search/urls.py
from django.urls import path
from .views import Search

app_name = 'search'

urlpatterns = [
    path('', Search.as_view(), name='search_page'),
]

src/apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>YOUR CHAT</title>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
<script type="text/javascript">
</script>
</html>

src/apps/templates/header.html
{% load static %}
<div class="header_container">
    <div class="header_menu">
        <form action="{% url 'search:search_page' %}" class='form_search'>
            <input name='q' type='text' placeholder="Search ..." />
        </form>
    </div>
    <div class="header_logo">
        <a href="{% url 'home:home_page' %}">YOURCHAT</a>
    </div>
    <div class="header_btn_logout">
        <div class="header_info_user">
            <p>Hi, <a href="{% url 'profile:profile_page' name=user.username %}">{{user.username}}</a></p>
        </div>
        <a class='btn_logout' href="{% url 'home:exit_page' %}">logout</a>
    </div>
</div>