config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('detail/', include('src.apps.detailchannel.urls', namespace='detail')),
    path('newchannel/', include('src.apps.newchannel.urls', namespace='newchannel')),
    path('search/', include('src.apps.search.urls', namespace='search')),
    path('profile/', include('src.apps.profile.urls', namespace='profile')),
    path('register/', include('src.apps.register.urls', namespace='register')),
    path('login/', include('src.apps.login.urls', namespace='login')),
    path('', include('src.apps.home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

src/apps/detailchannel/urls.py
from django.urls import path
from .views import Detail, Check

app_name = 'detail'

urlpatterns = [
    path('<int:pk>/', Detail.as_view(), name='detail_page'),
    path('<int:pk>/checkpassword/', Check.as_view(), name='check_page'),
]

src/apps/home/urls.py
from django.urls import path
from .views import Index
from src.apps.login.views import exit

app_name = 'home'

urlpatterns = [
    path('logout/', exit, name='exit_page'),
    path('', Index.as_view(), name='home_page'),
]

src/apps/newchannel/urls.py
from django.urls import path
from .views import NewChannel

app_name = 'newchannel'

urlpatterns = [
    path('', NewChannel.as_view(), name='newchannel_page'),
]

src/apps/profile/urls.py
from django.urls import path
from .views import Profile


app_name = 'profile'


urlpatterns = [
    path('<str:name>/', Profile.as_view(), name='profile_page'),
]

src/apps/home/views.py
from django.views import View
from django.http import HttpResponseRedirect
from django.shortcuts import render
from src.models.channel.models import Channel


class Index(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            channels = Channel.objects.all()
            return render(request, 'home/index.html', {'channels': channels})
        return HttpResponseRedirect('/login/')

src/apps/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'header.html' %}

    <div class="home_container">
        <div class="btn_new_chat">
            <a href="{% url 'newchannel:newchannel_page' %}">NEW CHHANNEL</a>
        </div>
        <h4>Lists channels</h4>

        <div class="list_channels">
            {% if channels %}
                {% for channel in channels %}
                    <div class="item_">
                        <a href="{% url 'detail:detail_page' pk=channel.pk  %}">{{channel.name}}</a>
                        {% if channel.password %}
                            <img src="{% static 'assets/padlock.png' %}" />
                        {% endif %}
                        <p>Author: <a href="{% url 'profile:profile_page' name=channel.author.username %}">{{channel.author}}</a></p>
                    </div>
                {% endfor%}
            {% else %}

            {% endif %}
        </div>

    </div>

<script src="{% static 'js/home.js' %}"></script>
{% endblock %}