config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('detail/', include('src.apps.detailchannel.urls', namespace='detail')),
    path('newchannel/', include('src.apps.newchannel.urls', namespace='newchannel')),
    path('search/', include('src.apps.search.urls', namespace='search')),
    path('profile/', include('src.apps.profile.urls', namespace='profile')),
    path('register/', include('src.apps.register.urls', namespace='register')),
    path('login/', include('src.apps.login.urls', namespace='login')),
    path('', include('src.apps.home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

src/apps/login/urls.py
from django.urls import path
from .views import Login

app_name = 'login'

urlpatterns = [
    path('', Login.as_view(), name='login_page'),
]

src/apps/register/urls.py
from django.urls import path
from .views import Register


app_name = 'register'


urlpatterns = [
    path('', Register.as_view(), name='register_page'),
]

src/apps/login/views.py
from django.views import View
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout



class Login(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/')
        return render(request, 'login/login.html', {})


    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponse('good')
        return HttpResponseNotFound('bad')


def exit(request):
    logout(request)
    return HttpResponseRedirect('/')

src/apps/templates/login/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


    <div class="login_container">
        <div class="login_form">
            <img class='login_checked' src="{% static 'assets/checked.png' %}" />
            <img class='login_error' src="{% static 'assets/error.png' %}" />
            <p>Hi, log in to your account</p>
            <form class='form_login'>{% csrf_token %}
                <input class='login_input' type='text' placeholder="Login ..." />
                <input class='password_input' type='password' placeholder="Password ..." />
                <button type='submit'>LOGIN</button>
            </form>
            <a class='bnt_register' href="{% url 'register:register_page' %}">register</a>
        </div>
    </div>
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}